source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AXRegex_Example', :exclusive => true do
  pod "AXRegex", :path => "../"
end

target 'AXRegex_Tests', :exclusive => true do
  pod "AXRegex", :path => "../"

  
end
